rm DMacDonell_thesis.aux
rm DMacDonell_thesis.lof
rm DMacDonell_thesis.log
rm DMacDonell_thesis.lop
rm DMacDonell_thesis.lot
rm DMacDonell_thesis.out
rm DMacDonell_thesis.toc
pdflatex DMacDonell_thesis.tex
pdflatex DMacDonell_thesis.tex
