name: msc_thesis
on: push
jobs:
  make_thesis:
    runs-on: ubuntu-latest
    container: blang/latex:ubuntu
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - run: |
          pdflatex DMacDonell_thesis.tex
          pdflatex DMacDonell_thesis.tex
         
      - uses: actions/upload-artifact@v2
        with:
          name: thesis_pdf
          path: DMacDonell_thesis.pdf

